#!/bin/sh
if [ -d ppr ]; then
	cd ppr
fi
git submodule update --remote git

echo "# Do not edit this file manually" > objs.mk
find git -name "*.c" | sed -E 's/\.c/$(O)/g' | while read a; do
	echo "OBJS += $a" >> objs.mk
done
